<a href="https://colab.research.google.com/github/AlejandroHernandez1802/NumpyFundamentals-DataScienceFundamentals/blob/master/NumpyChallenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [0]:

import numpy as np 

arr = np.array([7,8,4,5,1,2])
print(arr)


[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [0]:
import numpy as np

arr = np.array([7,8,4,5,1,2])
print(arr[2:])

[4 5 1 2]


Using slicing print all the elements except the last one.



In [0]:
import numpy as np

arr = np.array([7,8,4,5,1,2])
print(arr[ :-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [0]:
import numpy as np

arr = np.array([7,8,4,5,1,2])
print(arr[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [0]:
import numpy as np
print('Normal array: ')
arr = np.array([7,8,4,5,1,2])
print(arr)
print('Reshape array: ')
arr = np.reshape(arr,(3,2))
print(arr)

Normal array: 
[7 8 4 5 1 2]
Reshape array: 
[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
for i in arr:
  print(i)
  

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [0]:
import numpy as np  
arr2 = np.array([0,6,9])
print(arr2)

[0 6 9]


Join the two arrays.



In [0]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
arr2 = np.array([0,6,9])
FinalArr = np.concatenate((arr,arr2))
print(FinalArr)


[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [0]:
import numpy as np

arr = np.array([7,8,4,5,1,2,0,6,9])

filterarr = []

x = [True, False, True, False, True, False, True, False, True]

newarr = arr[x]

print(newarr)


[7 4 1 0 9]


Sort the joined array elements.



In [0]:

import numpy as np
arr = np.array([7,8,4,5,1,2,0,6,9])

arraysorted = np.sort(arr, axis = None)

print(arraysorted)

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [0]:
import numpy as np

arrMonths = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Agaust' , 'September', 'October', 'November', 'December'])
print(arrMonths)

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'Agaust'
 'September' 'October' 'November' 'December']


Split the months array in 4 periods of 3 elements each one.



In [0]:
import numpy as np
arrMonths = np.array(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'Agaust' , 'September', 'October', 'November', 'December'])
splitedArrayMonths = np.split(arrMonths, 3)
print(splitedArrayMonths)


[array(['January', 'February', 'March', 'April'], dtype='<U9'), array(['May', 'June', 'July', 'Agaust'], dtype='<U9'), array(['September', 'October', 'November', 'December'], dtype='<U9')]


Create an array with genre information ['F','M','F','F','M','F'].



In [0]:
import numpy as np
arr = np.array(('F','M','F','F','M','F'))
print(arr)


['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [0]:
import numpy as np
arr = np.array(('F','M','F','F','M','F'))
y=0
for x in arr:
  if x == 'F':
    print(y)
  y= y+1

0
2
3
5


Store in an array the age information [18,20,19,23,19,20].



In [0]:
import numpy as np
ageInformation = np.array([18,20,19,23,19,20])
print(ageInformation)


[18 20 19 23 19 20]


Create a filter array with values < 20.



In [0]:
import numpy as np

ageInformation = np.array([18,20,19,23,19,20])

for element in ageInformation:

  if element <= 20:
    np.append(ageInformation, True)
  else:
    np.append(ageInformation, False)

print(ageInformation)

[18 20 19 23 19 20]


Change the 3 index element with a value of 22



In [0]:
import numpy as np
arr = np.array((18,20,19,23,19,20))
arr[2] = 22
print(arr)

[18 20 22 23 19 20]


Print the 4 index element.

In [0]:
import numpy as np

ageInformation = np.array([18,20,19,23,19,20])

print(ageInformation[3])

23
